name: Test
on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.13', '1.14']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
      with:     
        go-version: ${{ matrix.go-version }}

    - name: Install golint
      run: go get -v -u golang.org/x/lint/golint

    - name: Vet     
      run: go vet ./...

    - name: Format
      if: matrix.platform != 'windows-latest'
      run: test -z $(gofmt -l .)

    - name: Lint
      run: golint -set_exit_status ./...

    - name: Test
      run: go test -race ./...
